using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Erp
{
    public partial class FrmUretilenIsEmirleri : Form
    {
        public FrmUretilenIsEmirleri()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource2.FillAsync();
        }

        private void FrmUretilenIsEmirleri_Load(object sender, EventArgs e)
        {
            gridView1.OptionsBehavior.Editable = false;
        }
    }
}
