using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.SqlClient;

namespace Erp
{
    public partial class FrmUretilecekIsEmirleri : Form
    {
        SqlConnection conn = new SqlConnection("Data Source=LAPTOP-SU16M9I9\\VT_SQL;Initial Catalog=ERP_EGITIM;Integrated Security=True");

        public FrmUretilecekIsEmirleri()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }
        void isemrilisteleme()
        {
            conn.Open();
            DataTable dt = new DataTable();
            SqlCommand sorgu1 = new SqlCommand("SELECT ISEMRI_NUMARASI,STOK_KODU,STOK_ADI,ISEMRI_ACIKLAMASI,SUBSTRING(ISEMRI_TARIHI,0,10) AS 'İŞ EMRİ TARİHİ', SUBSTRING(TESLIM_TARIHI,0,10) AS 'TESLİM TARİHİ',SIPARIS_NO,MIKTAR,SIPKALEM_ID FROM TBL_ISEMRI WHERE DURUM='Y'", conn);
            SqlDataAdapter da = new SqlDataAdapter(sorgu1);
            da.Fill(dt);
            gridControl1.DataSource = dt;
            conn.Close();
        }
        string x1 = "";
        void uretimsonukaydinumarasihesaplama()
        {
            conn.Open();
            SqlCommand sorgu1 = new SqlCommand("SELECT TOP 1 CONCAT('U',REPLICATE('0',10-(LEN(SUBSTRING(URETIMSONUKAYDI_NUMARASI,2,9)+1)+1)),SUBSTRING(URETIMSONUKAYDI_NUMARASI,2,9)+1) AS 'URETIM SONU KAYDI NUMARASI' FROM TBL_URETIMSONUKAYITLARI ORDER BY URETIMSONUKAYDI_NUMARASI DESC", conn);
            SqlDataReader dr = sorgu1.ExecuteReader();
            while (dr.Read())
            {
                x1 = dr[0].ToString();
            }
            conn.Close();

        }

        private void FrmUretilecekIsEmirleri_Load(object sender, EventArgs e)
        {
            // gridView1.OptionsBehavior.Editable = false;  üretim yap butonu çalışmadığı için bu kod kaldırıldı.
        }
        string sipno = "";
        string isemrino = "";

        private void repositoryItemButtonEdit1_ButtonClick(object sender, DevExpress.XtraEditors.Controls.ButtonPressedEventArgs e)
        {
            int x = gridView1.FocusedRowHandle; // tıklanılan satırın numarasını tutar
            isemrino = gridView1.GetRowCellValue(x,"ISEMRI_NUMARASI").ToString();
            sipno= gridView1.GetRowCellValue(x, "SIPARIS_NO").ToString();
            // MessageBox.Show(isemrino + sipno); calisiyor.
            DialogResult secim= MessageBox.Show("Seçili olan ürün üretilecektir emin misiniz","DİKKAT",MessageBoxButtons.YesNo,MessageBoxIcon.Exclamation);
            if (secim == DialogResult.Yes)
            {
                string stokkodu = "";
                string stokadi = "";
                string miktar = "";
                string sipkalemID = "";
                string musterikodu = "";
                string musteriadi = "";

                conn.Open();
                SqlCommand sorgu1 = new SqlCommand("SELECT * FROM TBL_ISEMRI WHERE ISEMRI_NUMARASI='"+isemrino+"'", conn);
                SqlDataReader dr1 = sorgu1.ExecuteReader();
                while (dr1.Read())
                {
                    stokkodu = dr1[1].ToString();
                    stokadi= dr1[2].ToString();
                    miktar= dr1[7].ToString();
                    sipkalemID= dr1[8].ToString();
                }
                conn.Close();

                conn.Open();
                SqlCommand sorgu2 = new SqlCommand("SELECT SIP.MUSTERI_KODU, MK.MUSTERI_ADI FROM TBL_SIPARISLER SIP LEFT JOIN TBL_MUSTERIKAYITLARI MK ON SIP.MUSTERI_KODU=MK.MUSTERI_KODU WHERE SIPARIS_NO='"+sipno+"'", conn);
                SqlDataReader dr2 = sorgu1.ExecuteReader();
                while (dr2.Read())
                {
                    musterikodu = dr2[0].ToString();
                    musteriadi = dr2[1].ToString();
                }
                conn.Close();
                

                uretimsonukaydinumarasihesaplama();

                conn.Open();
                SqlCommand sorgu3 = new SqlCommand("INSERT INTO TBL_URETIMSONUKAYITLARI(URETIMSONUKAYDI_NUMARASI,ISEMRI_NUMARASI,STOK_KODU,STOK_ADI,MIKTAR,SIPARIS_NUMARASI,SIPKALEM_ID,MUSTERI_KODU,MUSTERI_ADI) VALUES('" + x1 + "','" + isemrino + "','" + stokkodu + "','" + stokadi + "','" + miktar.Replace(',', '.') + "','" + sipno + "','" + sipkalemID + "','" + musterikodu + "','" + musteriadi + "')", conn);
                sorgu3.ExecuteNonQuery();
                conn.Close();

                conn.Open();
                SqlCommand sorgu4 = new SqlCommand("UPDATE TBL_ISEMRI SET DURUM='E' WHERE ISEMRI_NUMARASI='" + isemrino + "'", conn);
                sorgu4.ExecuteNonQuery();
                conn.Close();

                conn.Open();
                SqlCommand sorgu5 = new SqlCommand("UPDATE TBL_SIPARISKALEMLERI SET URETIMDURUMU='B' WHERE SIPKALEM_ID='" + sipkalemID + "'", conn);
                sorgu5.ExecuteNonQuery();
                conn.Close();

                conn.Open();
                SqlCommand sorgu6 = new SqlCommand("INSERT INTO TBL_STOKHAREKETLERI(URETIMSONUKAYDI_NUMARASI,ISEMRI_NUMARASI,STOK_KODU,STOK_ADI,G_MIKTAR,C_MIKTAR,MUSTERI_ADI,ACIKLAMA) VALUES('" + x1 + "','" + isemrino + "','" + stokkodu + "','" + stokadi + "','" + miktar.Replace(',', '.') + "','0','" + musteriadi + "','ÜRETİM')", conn);
                sorgu6.ExecuteNonQuery();
                conn.Close();

                isemrilisteleme();
                MessageBox.Show("Üretim Başarıyla Gerçekleşti!");
            }
            else
            {
                MessageBox.Show("Üretim İptal Edildi");
            }
        }
    }
}
